#!/usr/bin/env bash
# Bash script that displays "Best School" 10 times
counter=1
while [ $counter -le 10 ]
do
   echo "Best School"
   if [[ $counter -eq 9 ]];
   then
       echo "Hi"
   fi
   (( counter++ ))
done